### ISSUE TITLE
removeitem leaves selection box behind

### ISSUE THREAD

**Issue by rosaqq** [secknv/lekek#34]
![image](https://user-images.githubusercontent.com/16641477/107133466-3b319400-68e0-11eb-9052-870b0d0e7b81.png)

**Comment by dffsa** [comment]
solved with 642f030b9e54aeada666d6ef6fabf9572d71d0c9

**Comment by dffsa** [comment]
already fixed by 642f030b9e54aeada666d6ef6fabf9572d71d0c9
